import {
  Container,
  AppBar,
  Toolbar,
  Typography,
  Stack,
  Box,
} from '@mui/material';
import { Inter } from 'next/font/google';
import Image from 'next/image';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        {/* Header with logo */}
        <AppBar>
          <Toolbar>
            <Container maxWidth='sm' sx={{ display: 'flex' }}>
              <Stack
                direction='row'
                width='100%'
                spacing={2}
                justifyContent='space-between'
              >
                <Image
                  src='/anytime_labs_white.png'
                  alt='Logo'
                  width={200}
                  height={25}
                />
                <Typography variant='h6' component='div'>
                  Example Client
                </Typography>
              </Stack>
            </Container>
          </Toolbar>
        </AppBar>

        {/* Main content */}
        <Container maxWidth='sm' sx={{ paddingTop: '80px' }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
